version: '3.8'

networks:
  helpdesk_sql_network:
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver_container
    networks:
      helpdesk_sql_network:
        ipv4_address: 192.168.100.10
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "HelpDesk@123"
      ACCEPT_EULA: "Y"
    restart: unless-stopped
